backend:
  # name: test-repo
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port
local_backend: true

media_folder: static/images
public_folder: /images
display_url: https://deftwire.com

collections:
  - name: 'author'
    label: 'Author'
    folder: 'content/authors'
    create: true
    identifier_field: name
    editor:
      preview: false
    fields:
      - name: name
        label: Full Name
        widget: string
      - name: email
        label: Email
        widget: string
      - name: avatar
        label: Avatar Image
        hint: Upload a square image please!
        widget: image
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{tags.title}}'
    identifier_field: tags.title
    summary: '{{date}} - {{tags.title}}'
    sortable_fields: ['date', tags.title', 'commit_author']
    editor:
      preview: false
    fields:
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'author',
          value_field: 'email',
          display_fields: ['name'],
          search_fields: ['name', 'email'],
          default: 'Gabe Rench',
        }
      - name: date
        label: Post Date
        widget: datetime
        date_format: true
        time_format: true
      - name: tags
        label: Meta
        widget: 'metatags'
