backend:
  # name: test-repo
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port
local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    preview_path_date_field: date
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    identifier_field: tags.title
    sortable_fields: ['date', 'tags.title']
    editor:
      preview: false
    fields:
      - name: date
        label: Post Date
        widget: date
        format: YYYY-MM-DD
      - name: tags
        label: Meta
        widget: 'metatags'
