backend:
  # name: test-repo
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port
local_backend: true

media_folder: static/images
public_folder: /images
display_url: https://deftwire.com

collections:
  - name: 'author'
    label: 'Author'
    folder: 'content/authors'
    create: true
    identifier_field: name
    fields:
      - name: name
        label: Full Name
      - name: avatar
        label: Avatar Image
        hint: Upload a square image please!
        widget: image
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{tags.title}}'
    identifier_field: tags.title
    summary: '{{date}} - {{tags.title}}'
    sortable_fields: ['date', tags.title', 'commit_author']
    editor:
      preview: false
    fields:
      - name: 'author'
        label: 'Post Author'
        widget: 'relation'
        collection: 'authors'
        search_fields: ['name']
        value_field: 'name'
      - name: date
        label: Post Date
        widget: datetime
        date_format: true
        time_format: true
      - name: tags
        label: Meta
        widget: 'metatags'
