backend:
  # name: test-repo
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    editor:
      preview: false
    fields:
      - name: title
        label: title
        widget: string
        required: false
      - name: meta
        label: Meta
        widget: 'metatags'
